token: abcde
server:
  port: 10002
spring:
  application:
    name: user-consumer
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8004
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:8001/eureka/
feign:
  hystrix:
    enabled: true
